// Code generated by scripts/gen_provider_profiles.py; DO NOT EDIT.
// Source: pi-ai 0.82.1 dist/providers/data/*.json (deepseek-harness rc.2).
// Regenerate: python scripts/gen_provider_profiles.py

package model

func init() {
	registerProviderProfile(ProviderProfile{
		Provider:     "amazon-bedrock",
		EffortFormat: EffortBedrock,
		Models: map[string]ModelProfile{
			"anthropic.claude-fable-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"anthropic.claude-opus-4-6-v1": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"anthropic.claude-opus-4-7": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"anthropic.claude-opus-4-8": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"anthropic.claude-sonnet-4-6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"anthropic.claude-sonnet-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"au.anthropic.claude-opus-4-6-v1": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"au.anthropic.claude-opus-4-8": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"au.anthropic.claude-opus-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"au.anthropic.claude-sonnet-4-6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"au.anthropic.claude-sonnet-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"eu.anthropic.claude-fable-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"eu.anthropic.claude-opus-4-6-v1": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"eu.anthropic.claude-opus-4-7": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"eu.anthropic.claude-opus-4-8": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"eu.anthropic.claude-opus-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"eu.anthropic.claude-sonnet-4-6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"eu.anthropic.claude-sonnet-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"global.anthropic.claude-fable-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"global.anthropic.claude-opus-4-6-v1": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"global.anthropic.claude-opus-4-7": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"global.anthropic.claude-opus-4-8": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"global.anthropic.claude-opus-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"global.anthropic.claude-sonnet-4-6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"global.anthropic.claude-sonnet-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"jp.anthropic.claude-opus-4-7": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"jp.anthropic.claude-opus-4-8": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"jp.anthropic.claude-opus-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"jp.anthropic.claude-sonnet-4-6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"jp.anthropic.claude-sonnet-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"openai.gpt-5.4": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai.gpt-5.5": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai.gpt-5.6-luna": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai.gpt-5.6-sol": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai.gpt-5.6-terra": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"us.anthropic.claude-fable-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"us.anthropic.claude-opus-4-6-v1": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"us.anthropic.claude-opus-4-7": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"us.anthropic.claude-opus-4-8": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"us.anthropic.claude-opus-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"us.anthropic.claude-sonnet-4-6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"us.anthropic.claude-sonnet-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "ant-ling",
		EffortFormat: EffortAntLing,
		Models: map[string]ModelProfile{
			"Ring-2.6-1T": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"medium": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "azure-openai-responses",
		EffortFormat: EffortOpenAI,
		Models: map[string]ModelProfile{
			"gpt-5": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gpt-5-chat-latest": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gpt-5-mini": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gpt-5-nano": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gpt-5-pro": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gpt-5.1": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gpt-5.2": {
				EffortLevels: EffortLevelMap{
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.2-chat-latest": {
				EffortLevels: EffortLevelMap{
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.2-pro": {
				EffortLevels: EffortLevelMap{
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.3-chat-latest": {
				EffortLevels: EffortLevelMap{
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.3-codex": {
				EffortLevels: EffortLevelMap{
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.3-codex-spark": {
				EffortLevels: EffortLevelMap{
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4": {
				EffortLevels: EffortLevelMap{
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4-mini": {
				EffortLevels: EffortLevelMap{
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4-nano": {
				EffortLevels: EffortLevelMap{
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4-pro": {
				EffortLevels: EffortLevelMap{
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.5": {
				EffortLevels: EffortLevelMap{
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.5-pro": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-luna": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-sol": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-terra": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "cerebras",
		EffortFormat: EffortOpenAI,
		Models: map[string]ModelProfile{
			"gemma-4-31b": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": nil,
				},
			},
			"gpt-oss-120b": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"zai-glm-4.7": {
				EffortLevels: EffortLevelMap{
					"high": nil,
					"low": nil,
					"max": nil,
					"medium": nil,
					"minimal": nil,
					"off": "none",
					"xhigh": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "cloudflare-ai-gateway",
		EffortFormat: EffortAnthropic,
		Models: map[string]ModelProfile{
			"claude-fable-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"claude-opus-4-6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"claude-opus-4-7": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"claude-opus-4-8": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"claude-sonnet-4-6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"claude-sonnet-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.1": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5.1-codex": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5.2": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.2-codex": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.3-codex": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.5": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-luna": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-sol": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-terra": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"o1": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"o3": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"o3-mini": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"o3-pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"o4-mini": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "cloudflare-workers-ai",
		EffortFormat: EffortOpenAI,
		Models: map[string]ModelProfile{
			"@cf/google/gemma-4-26b-a4b-it": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"@cf/moonshotai/kimi-k2.6": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"@cf/moonshotai/kimi-k2.7-code": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"@cf/nvidia/nemotron-3-120b-a12b": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"@cf/openai/gpt-oss-120b": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"@cf/zai-org/glm-4.7-flash": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"@cf/zai-org/glm-5.2": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "fireworks",
		EffortFormat: EffortOpenAI,
		Models: map[string]ModelProfile{
			"accounts/fireworks/models/glm-5p2": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "high",
					"max": "max",
					"medium": "high",
					"minimal": nil,
					"off": "none",
					"xhigh": nil,
				},
			},
			"accounts/fireworks/routers/glm-5p2-fast": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "high",
					"max": "max",
					"medium": "high",
					"minimal": nil,
					"off": "none",
					"xhigh": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "github-copilot",
		EffortFormat: EffortAnthropic,
		Models: map[string]ModelProfile{
			"claude-fable-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"claude-opus-4.6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"claude-opus-4.7": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"minimal": "low",
					"xhigh": "xhigh",
				},
			},
			"claude-opus-4.8": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"minimal": "low",
					"xhigh": "xhigh",
				},
			},
			"claude-opus-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"claude-sonnet-4.6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"minimal": "low",
				},
			},
			"claude-sonnet-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"gpt-5-mini": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": "low",
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5.2": {
				EffortLevels: EffortLevelMap{
					"minimal": "low",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.2-codex": {
				EffortLevels: EffortLevelMap{
					"minimal": "low",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.3-codex": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": "low",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": "low",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4-mini": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": "low",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4-nano": {
				EffortLevels: EffortLevelMap{
					"minimal": "low",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.5": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": "low",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-luna": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": "medium",
					"minimal": "low",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-sol": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": "medium",
					"minimal": "low",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-terra": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": "medium",
					"minimal": "low",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"mai-code-1-flash-picker": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "google-vertex",
		EffortFormat: EffortGoogle,
		Models: map[string]ModelProfile{
			"gemini-3-flash-preview": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gemini-3.1-flash-lite": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gemini-3.1-pro-preview": {
				EffortLevels: EffortLevelMap{
					"high": "HIGH",
					"low": "LOW",
					"medium": nil,
					"minimal": nil,
					"off": nil,
				},
			},
			"gemini-3.1-pro-preview-customtools": {
				EffortLevels: EffortLevelMap{
					"high": "HIGH",
					"low": "LOW",
					"medium": nil,
					"minimal": nil,
					"off": nil,
				},
			},
			"gemini-3.5-flash": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gemini-3.5-flash-lite": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gemini-3.6-flash": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gemini-flash-latest": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gemini-flash-lite-latest": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "groq",
		EffortFormat: EffortOpenAI,
		Models: map[string]ModelProfile{
			"openai/gpt-oss-120b": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"openai/gpt-oss-20b": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"openai/gpt-oss-safeguard-20b": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"qwen/qwen3-32b": {
				EffortLevels: EffortLevelMap{
					"high": "default",
					"low": nil,
					"max": nil,
					"medium": nil,
					"minimal": nil,
					"off": "none",
					"xhigh": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "huggingface",
		EffortFormat: EffortOpenAI,
		Models: map[string]ModelProfile{
			"Qwen/Qwen3.5-397B-A17B": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": nil,
				},
			},
			"XiaomiMiMo/MiMo-V2.5": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": "xhigh",
				},
			},
			"XiaomiMiMo/MiMo-V2.5-Pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": "xhigh",
				},
			},
			"deepseek-ai/DeepSeek-V4-Pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": nil,
					"medium": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"openai/gpt-oss-120b": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"openai/gpt-oss-20b": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"stepfun-ai/Step-3.7-Flash": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "kimi-coding",
		EffortFormat: EffortAnthropic,
		Models: map[string]ModelProfile{
			"k3": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"k3-256k": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "moonshotai-cn",
		EffortFormat: EffortDeepSeek,
		Models: map[string]ModelProfile{
			"kimi-k2.7-code": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"kimi-k2.7-code-highspeed": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"kimi-k3": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "openai",
		EffortFormat: EffortOpenAI,
		Models: map[string]ModelProfile{
			"gpt-5": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": "minimal",
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5-chat-latest": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gpt-5-mini": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": "minimal",
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5-nano": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": "minimal",
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5-pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": nil,
					"medium": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5.1": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": nil,
				},
			},
			"gpt-5.2": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.2-chat-latest": {
				EffortLevels: EffortLevelMap{
					"high": nil,
					"low": nil,
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.2-pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.3-chat-latest": {
				EffortLevels: EffortLevelMap{
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.3-codex": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.3-codex-spark": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4-mini": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4-nano": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4-pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.5": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.5-pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-luna": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-sol": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-terra": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": "medium",
					"minimal": nil,
					"off": "none",
					"xhigh": "xhigh",
				},
			},
			"gpt-realtime-2.1": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": "minimal",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"o1": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"o1-pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"o3": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"o3-mini": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"o3-pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"o4-mini": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "openai-codex",
		EffortFormat: EffortOpenAI,
		Models: map[string]ModelProfile{
			"gpt-5.3-codex-spark": {
				EffortLevels: EffortLevelMap{
					"minimal": "low",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4": {
				EffortLevels: EffortLevelMap{
					"minimal": "low",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4-mini": {
				EffortLevels: EffortLevelMap{
					"minimal": "low",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.5": {
				EffortLevels: EffortLevelMap{
					"minimal": "low",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-luna": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"minimal": "low",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-sol": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"minimal": "low",
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-terra": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"minimal": "low",
					"xhigh": "xhigh",
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "opencode",
		EffortFormat: EffortAnthropic,
		Models: map[string]ModelProfile{
			"claude-fable-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"claude-opus-4-6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"claude-opus-4-7": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"claude-opus-4-8": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"claude-opus-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"claude-sonnet-4-6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"claude-sonnet-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"deepseek-v4-flash": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": "max",
					"medium": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"deepseek-v4-flash-free": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": "max",
					"medium": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"deepseek-v4-pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": "max",
					"medium": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"gemini-3-flash": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gemini-3.1-pro": {
				EffortLevels: EffortLevelMap{
					"high": "HIGH",
					"low": "LOW",
					"medium": nil,
					"minimal": nil,
					"off": nil,
				},
			},
			"gemini-3.5-flash": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gemini-3.5-flash-lite": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"gemini-3.6-flash": {
				EffortLevels: EffortLevelMap{
					"off": nil,
				},
			},
			"glm-5.2": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": "max",
					"medium": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": "minimal",
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5-codex": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5-nano": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": "minimal",
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5.1": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5.1-codex": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5.1-codex-max": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.1-codex-mini": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"gpt-5.2": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.2-codex": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.3-codex": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4-mini": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4-nano": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.4-pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.5": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.5-pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-luna": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-sol": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"gpt-5.6-terra": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": "max",
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"grok-4.5": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"grok-build-0.1": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"medium": nil,
					"minimal": nil,
					"off": nil,
				},
			},
			"laguna-s-2.1-free": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"ling-3.0-flash-free": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"north-mini-code-free": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": nil,
					"medium": nil,
					"minimal": nil,
					"off": "none",
					"xhigh": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "opencode-go",
		EffortFormat: EffortDeepSeek,
		Models: map[string]ModelProfile{
			"deepseek-v4-flash": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": "max",
					"medium": nil,
					"minimal": nil,
				},
			},
			"deepseek-v4-pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": "max",
					"medium": nil,
					"minimal": nil,
				},
			},
			"glm-5.2": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": "max",
					"medium": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"grok-4.5": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"hy3": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": nil,
					"minimal": nil,
					"off": "none",
					"xhigh": nil,
				},
			},
			"kimi-k2.6": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"medium": nil,
					"minimal": nil,
				},
			},
			"kimi-k3": {
				EffortLevels: EffortLevelMap{
					"high": nil,
					"low": nil,
					"max": "max",
					"medium": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "qwen-token-plan",
		EffortFormat: EffortDeepSeek,
		Models: map[string]ModelProfile{
			"deepseek-v4-flash": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": "max",
					"medium": nil,
					"minimal": nil,
				},
			},
			"deepseek-v4-pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": "max",
					"medium": nil,
					"minimal": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "qwen-token-plan-cn",
		EffortFormat: EffortDeepSeek,
		Models: map[string]ModelProfile{
			"deepseek-v4-flash": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": "max",
					"medium": nil,
					"minimal": nil,
				},
			},
			"deepseek-v4-pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"max": "max",
					"medium": nil,
					"minimal": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "together",
		EffortFormat: EffortOpenAI,
		Models: map[string]ModelProfile{
			"MiniMaxAI/MiniMax-M2.7": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"medium": nil,
					"minimal": nil,
					"off": nil,
				},
			},
			"MiniMaxAI/MiniMax-M3": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"medium": nil,
					"minimal": nil,
				},
			},
			"Qwen/Qwen3.5-9B": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"medium": nil,
					"minimal": nil,
				},
			},
			"Qwen/Qwen3.6-Plus": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"medium": nil,
					"minimal": nil,
				},
			},
			"deepseek-ai/DeepSeek-V4-Pro": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": nil,
					"medium": nil,
					"minimal": nil,
					"xhigh": nil,
				},
			},
			"google/gemma-4-31B-it": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"medium": nil,
					"minimal": nil,
				},
			},
			"moonshotai/Kimi-K2.6": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"medium": nil,
					"minimal": nil,
				},
			},
			"moonshotai/Kimi-K2.7-Code": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"medium": nil,
					"minimal": nil,
				},
			},
			"nvidia/nemotron-3-ultra-550b-a55b": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"medium": nil,
					"minimal": nil,
				},
			},
			"openai/gpt-oss-120b": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"openai/gpt-oss-20b": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
			"thinkingmachines/Inkling": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"medium": nil,
					"minimal": nil,
				},
			},
			"zai-org/GLM-5.2": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"medium": nil,
					"minimal": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "vercel-ai-gateway",
		EffortFormat: EffortAnthropic,
		Models: map[string]ModelProfile{
			"anthropic/claude-fable-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"anthropic/claude-opus-4.6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"anthropic/claude-opus-4.7": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"anthropic/claude-opus-4.8": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"anthropic/claude-opus-4.8-fast": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"anthropic/claude-opus-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"anthropic/claude-opus-5-fast": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"anthropic/claude-sonnet-4.6": {
				EffortLevels: EffortLevelMap{
					"max": "max",
				},
			},
			"anthropic/claude-sonnet-5": {
				EffortLevels: EffortLevelMap{
					"max": "max",
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.2": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.2-codex": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.2-pro": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.3-chat": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.3-codex": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.4": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.4-mini": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.4-nano": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.4-pro": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.5": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.5-pro": {
				EffortLevels: EffortLevelMap{
					"low": nil,
					"minimal": nil,
					"off": nil,
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.6-luna": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.6-sol": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
			"openai/gpt-5.6-terra": {
				EffortLevels: EffortLevelMap{
					"xhigh": "xhigh",
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "xai",
		EffortFormat: EffortOpenAI,
		Models: map[string]ModelProfile{
			"grok-4.5": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "low",
					"max": nil,
					"medium": "medium",
					"minimal": nil,
					"off": nil,
					"xhigh": nil,
				},
			},
		},
	})
	registerProviderProfile(ProviderProfile{
		Provider:     "zai-coding-cn",
		EffortFormat: EffortZAI,
		Models: map[string]ModelProfile{
			"glm-5.2": {
				EffortLevels: EffortLevelMap{
					"high": "high",
					"low": "high",
					"max": "max",
					"medium": "high",
					"minimal": nil,
				},
			},
		},
	})
}

