# -*- coding: utf-8 -*-
"""Generate Go provider profile data from pi-ai dist data/*.json.

Output: E:\\test\\rewrite-agently\\inferglow-github\\model\\provider_profiles_gen.go
The generated file registers ProviderProfile entries (provider -> per-model
EffortLevelMap + EffortFormat) for every provider whose models declare a
thinkingLevelMap or a compat.thinkingFormat.

Format mapping (pi-ai compat.thinkingFormat -> model.EffortWireFormat):
  openai       -> EffortOpenAI
  deepseek     -> EffortDeepSeek
  openrouter   -> EffortOpenRouter
  together     -> EffortTogether
  zai          -> EffortZAI
  qwen         -> EffortQwen
  ant-ling     -> EffortAntLing
  (google / anthropic / mistral / bedrock are inferred from api protocol when
   compat.thinkingFormat is absent)
"""
import json
import glob
import os

DATA_DIR = r"C:\nvm\v22.22.1\node_modules\@deepseek-ai\dsh\node_modules\@earendil-works\pi-ai\dist\providers\data"
OUT = r"E:\test\rewrite-agently\inferglow-github\model\provider_profiles_gen.go"

FORMAT_BY_COMPAT = {
    "openai": "EffortOpenAI",
    "deepseek": "EffortDeepSeek",
    "openrouter": "EffortOpenRouter",
    "together": "EffortTogether",
    "zai": "EffortZAI",
    "qwen": "EffortQwen",
    "ant-ling": "EffortAntLing",
}

# api protocol -> default wire format when compat.thinkingFormat absent
FORMAT_BY_API = {
    "openai-completions": "EffortOpenAI",
    "openai-responses": "EffortOpenAI",
    "azure-openai-responses": "EffortOpenAI",
    "openai-codex-responses": "EffortOpenAI",
    "anthropic-messages": "EffortAnthropic",
    "google-generative-ai": "EffortGoogle",
    "google-vertex": "EffortGoogle",
    "mistral-conversations": "EffortMistral",
    "bedrock-converse-stream": "EffortBedrock",
}

# Providers with no interesting data (no thinkingLevelMap anywhere) are skipped
# from the generated registry (they fall back to provider-level defaults).

# Providers hand-curated in provider_profile.go (authoritative, e.g. DSH
# llm-deepseek off/low/high/max) — the generator must NOT overwrite them.
HAND_CURATED = {
    "deepseek", "openrouter", "zai", "google", "anthropic", "mistral",
    "qwen", "moonshotai",
}

def go_literal(v):
    if v is None:
        return "nil"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return json.dumps(v)  # double-quoted, escapes
    return json.dumps(v)


def build():
    providers = {}  # provider -> {"format": fmt, "models": {model: {level: wire}}}
    for path in sorted(glob.glob(os.path.join(DATA_DIR, "*.json"))):
        prov = os.path.basename(path)[:-5]
        if prov in HAND_CURATED:
            continue  # hand-curated profiles win (authoritative DSH facts)
        try:
            data = json.load(open(path, encoding="utf-8"))
        except Exception:
            continue
        models = {}
        prov_format = None
        for api, mods in data.items():
            if not isinstance(mods, dict):
                continue
            for mid, m in mods.items():
                if not isinstance(m, dict):
                    continue
                tlm = m.get("thinkingLevelMap")
                compat = m.get("compat") or {}
                if not isinstance(tlm, dict) or not tlm:
                    continue
                fmt = None
                cf = compat.get("thinkingFormat")
                if isinstance(cf, str) and cf in FORMAT_BY_COMPAT:
                    fmt = FORMAT_BY_COMPAT[cf]
                elif isinstance(cf, str) and cf == "chat-template":
                    fmt = "EffortOpenAI"  # chat-template uses chat_template_kwargs; treat as openai passthrough
                elif api in FORMAT_BY_API:
                    fmt = FORMAT_BY_API[api]
                else:
                    fmt = "EffortOpenAI"
                if prov_format is None:
                    prov_format = fmt
                level_map = {}
                for level, wire in tlm.items():
                    level_map[level] = go_literal(wire)
                models[mid] = level_map
        if models:
            providers[prov] = {"format": prov_format or "EffortOpenAI", "models": models}

    lines = []
    lines.append("// Code generated by scripts/gen_provider_profiles.py; DO NOT EDIT.")
    lines.append("// Source: pi-ai 0.82.1 dist/providers/data/*.json (deepseek-harness rc.2).")
    lines.append("// Regenerate: python scripts/gen_provider_profiles.py")
    lines.append("")
    lines.append("package model")
    lines.append("")
    lines.append("func init() {")
    for prov in sorted(providers):
        p = providers[prov]
        lines.append(f"\tregisterProviderProfile(ProviderProfile{{")
        lines.append(f"\t\tProvider:     {json.dumps(prov)},")
        lines.append(f"\t\tEffortFormat: {p['format']},")
        lines.append(f"\t\tModels: map[string]ModelProfile{{")
        for mid in sorted(p["models"]):
            lm = p["models"][mid]
            lines.append(f"\t\t\t{json.dumps(mid)}: {{")
            lines.append(f"\t\t\t\tEffortLevels: EffortLevelMap{{")
            for lv in sorted(lm):
                lines.append(f"\t\t\t\t\t{json.dumps(lv)}: {lm[lv]},")
            lines.append(f"\t\t\t\t}},")
            lines.append(f"\t\t\t}},")
        lines.append(f"\t\t}},")
        lines.append(f"\t}})")
    lines.append("}")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("written", OUT)
    print("providers:", len(providers))
    print("lines:", len(lines))


if __name__ == "__main__":
    build()
